apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mgzx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-mgzx@sha256:727f4a24a23773407a4a45b6753f37bec73322bf8e4f18e3c8010a64e1553725
        name: my-nodejs
        resources: {}
status: {}
